name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -Pnative -Dquarkus.native.container-build=true -DskipTests -Dquarkus.dynamodb.aws.credentials.static-provider.access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} -Dquarkus.dynamodb.aws.credentials.static-provider.secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy with sam
        run: sam deploy --stack-name StackTestingV2 --s3-bucket acodemylambdabucket --capabilities CAPABILITY_IAM --force-upload
